---
slug: foobaz
filename: foobaz
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 5631aafb-3c03-4159-857d-85e44e10b90d
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
